= GIT
:toc:

<<../author/shamil.adoc#, Author>>

[[workflow]]
== Workflows
GIT is very powerful and complex version control system, allowing to implement different workflows for various purposes.

[[workflow-backup]]
== Backup
Some time ago https://github.com[GitHub] announced generous offer, unlimited amount of private repositories.
That means you can use it as backup of your configurations.

So you get for free except of backup:
[square]
* versioning;
* Web interface for viewing and editing;
* audit of made changes.

CAUTION: Think about confidential data in configurations.

[[workflow-backup-example]]
=== Example of backup for /etc/nginx of *pzdc.de*
Create new repo: https://github.com/new with name *pzdc.de-etc-nginx*

Copy *SSH* URL, e.g: *git@github.com:Pingvin235/pzdc.de-etc-nginx.git*

Take <<../network/ssh.adoc#keys, public SSH key>> and add it to link:https://github.com/settings/keys

Create local GIT repo:
[source, bash]
----
cd /etc/nginx
git init && git add . && git commit -m "Init"
git remote add origin git@github.com:Pingvin235/pzdc.de-etc-nginx.git
git push -u origin master
----

Do after any change:
[source, bash]
----
git add . && git push origin master
----

[[workflow-one-direction]]
== One direction
The workflow may be useful for remote update of static Web sites content or configurations.

