= Intro
:toc:

<<author/shamil.adoc#, Author>>

[[about]]
== About
This books is a Wiki-like knowledge base written on the open way on link:https://github.com/Pingvin235/book[GitHub].
Here are collected different hints and tips for software developers.

As a markup language used AsciiDoctor, converted using generator link:https://pzdcdoc.org[PzdcDoc] to static HTML pages.
You can edit *.adoc* files in every text editor or use link:https://pzdcdoc.org/demo/src/doc/demo.html#tools[IDE plugins].

[[prerequisites]]
== Prerequisites
The following programs have to be installed on machine to edit the book. Use the links for Windows installers or search them by name in OS package manager.
[square]
* GIT for working with <<#repo, repo>>
** link:https://git-scm.com/downloads[GIT for Windows]
* OpenJDK 11 or 17 for <<#build, build>>
** link:https://adoptium.net[OpenJDK for Windows]

[[repo]]
== Repository
Clone:
[source]
----
git clone https://github.com/Pingvin235/book.git Book
----

Create own branch:
----
git checkout -B my-branch
----

Commit all the changes:
----
git add . && git commit -m "Comment"
----

Push commit to GitHub:
----
git push
----

Apply latest changes from `master` to your branch:
----
git fetch origin master:master && git merge master
----

After your work in branch is done, send a Pull Request to GitHub for accepting your changes to master.

[[build]]
== Build
Execute in <<#repo, repo>> directory command `./gradlew`.
The result is placed in `target/doc`, `index.html` can be opened using browser.

////
[WARNING]
====
Для преобразования link:https://pzdcdoc.org/demo/src/doc/demo.html#diagrams-drawio[Draw.IO] диаграмм используется контейнер,
расположенный на сервере `drawio.pzdcdoc.org`. В случае его недоступности либо медленной работы,
запустите свой собственный Docker контейнер командой:
[source]
----
docker run -d -p 5000:5000 --shm-size=1g tomkludy/drawio-renderer:latest
----

Перенаправьте имя `drawio.pzdcdoc.org` на адрес 127.0.0.1 в файле `hosts`.
====
////

[[guide]]
== Guidelines
Place author reference at beginning of every file.

Case there is a good article exist in Net - place a link to it.
To do not loose content in the future use https://archive.is/.
Example of stored reference: https://archive.is/wip/TJsIF[https://bgerp.ru]

Here may be found link:https://pzdcdoc.org/demo/src/doc/demo.html[examples] of AsciiDoc markup.

The <<changes.adoc#, log>> is used for tracking changes.

AsciiDoc files and internal anchors have to be named using Latin alphanumeric symbols and *-*.

////
[[lang]]
== Многоязычность
Каждый *article.adoc* файл может быть написан на любом языке.
Аббревиатура языка оригинала должен быть указан в квадратных скобках после заголовка статьи.
При выполнении переводов файлы должны называться *article.<LANG_TO>.adoc* и располагаться рядом с оригинальным файлом.

В данный момент поддержка переводов не выполнена, но в перспективе предполагается, что под каждый язык ссылки внутри
файла будут корректироваться для указания на переводной вариант, если он есть.

Ссылка на файл описания переводчика должна быть размещена в начале файла после ссылки на автора.
////