= Введение [RU]
:toc:

<<dev/shamil.adoc#, Автор>>

[[about]]
== О книге
Данная книга представляет из себя базу знаний по IT технологиям наподобие Wiki,
но пишется открытым способом в link:https://github.com/Pingvin235/book[GitHub].

В качестве языка разметки применяется AsciiDoctor, преобразуемый с помощью генератора link:https://pzdcdoc.org[PzdcDoc] в HTML страницы.
Править *.adoc* файлы можно в любом текстовом редакторе, 
либо воспользоваться link:https://pzdcdoc.org/demo/src/doc/demo.html#tools[плагинами] для IDE.

[[prerequisites]]
== Необходимо установить
Следующие программы должны быть предустановлены на машине разработчика из репозитория пакетов ОС, либо по ссылке на наименовании программы.
[square]
* link:https://git-scm.com/downloads[GIT] для работы с <<#repo, репозиторием>>.
* link:https://adoptopenjdk.net/[OpenJDK 11] для <<#build, сборки>>.

[[repo]]
== Работа с репозиторием
Клонирование:
[source]
----
git clone https://github.com/Pingvin235/book.git Book
----

Создание собственной ветки:
----
git checkout -B my-branch
----

Получение последних изменений в `master`:
----
git fetch origin master:master
----

Слияние их на свою ветку:
----
git merge master
----

Отправка изменений ветки в GitHub:
----
git push
----

После того как работа в ветке завершена, отправьте Pull Request в GitHub для принятия их в основную ветку и публикации.

[[build]]
== Сборка
Выполните в каталоге <<#repo, репозитория>> команду `./gradlew`. 
Результат располагается в каталоге `target/doc`, `index.html` файл может быть открыт браузером.

[WARNING]
====
Для преобразования link:https://pzdcdoc.org/demo/src/doc/demo.html#diagrams-drawio[Draw.IO] диаграмм используется контейнер, 
расположенный на сервере `drawio.pzdcdoc.org`. В случае его недоступности либо медленной работы, 
запустите свой собственный Docker контейнер командой: 
[source]
----
docker run -d -p 5000:5000 --shm-size=1g tomkludy/drawio-renderer:latest
----

Перенаправьте имя `drawio.pzdcdoc.org` на адрес 127.0.0.1 в файле `hosts`.
====

[[recommendations]]
== Рекомендации авторам
Если где-то в Сети уже есть хорошее руководство - проще разместить ссылку на него.
Для предотвращения утери в будущем - можно использовать https://archive.is/.
Пример сохранённой ссылки на https://archive.is/wip/TJsIF[https://bgerp.ru]

Избегайте больших файлов, они увеличивают размер GIT.

Здесь можно посмотреть link:https://pzdcdoc.org/demo/src/doc/demo.html[примеры] разметки, там же есть ссылка на исходный файл AsciiDoc.

Для отслеживания изменений присутствует <<changes.adoc#, лог>>.

Ссылка на файл описания автора должна быть размещена в начале каждого файла.

[[lang]]
== Многоязычность
Каждый *article.adoc* файл может быть написан на любом языке.
Аббревиатура языка оригинала должен быть указан в квадратных скобках после заголовка статьи.
При выполнении переводов файлы должны называться *article.<LANG_TO>.adoc* и располагаться рядом с оригинальным файлом.

В данный момент поддержка переводов не выполнена, но в перспективе предполагается, что под каждый язык ссылки внутри
файла будут корректироваться для указания на переводной вариант, если он есть.

Ссылка на файл описания переводчика должна быть размещена в начале файла после ссылки на автора.
