= Introduction
:toc:

<<author/shamil.adoc#, Author>>

[[about]]
== About
This books is a Wiki-like knowledge base written on the open way on link:https://github.com/Pingvin235/book[GitHub]

As a markup language used AsciiDoctor, converted using generator link:https://pzdcdoc.org[PzdcDoc] to static HTML pages.
You can edit *.adoc* files in every text editor or use link:https://pzdcdoc.org/demo/src/doc/demo.html#tools[IDE plugins].

[[prerequisites]]
== Prerequisites
Следующие программы должны быть предустановлены на машине разработчика из репозитория пакетов ОС, либо по ссылке на наименовании программы.
[square]
* link:https://git-scm.com/downloads[GIT] для работы с <<#repo, репозиторием>>.
* link:https://adoptopenjdk.net/[OpenJDK 11] для <<#build, сборки>>.

[[repo]]
== Work with repository
Clone:
[source]
----
git clone https://github.com/Pingvin235/book.git Book
----

Create own branch:
----
git checkout -B my-branch
----

Commit all the changes:
----
git add . && git commit -m "Comment"
----

Push commit to GitHub:
----
git push
----

Apply latest changes from `master` to your branch:
----
git fetch origin master:master && git merge master
----

After your work in branch is done, send a Pull Request to GitHub for accepting your changes to master.

[[build]]
== Build
Выполните в каталоге <<#repo, репозитория>> команду `./gradlew`.
Результат располагается в каталоге `target/doc`, `index.html` файл может быть открыт браузером.

[WARNING]
====
Для преобразования link:https://pzdcdoc.org/demo/src/doc/demo.html#diagrams-drawio[Draw.IO] диаграмм используется контейнер,
расположенный на сервере `drawio.pzdcdoc.org`. В случае его недоступности либо медленной работы,
запустите свой собственный Docker контейнер командой:
[source]
----
docker run -d -p 5000:5000 --shm-size=1g tomkludy/drawio-renderer:latest
----

Перенаправьте имя `drawio.pzdcdoc.org` на адрес 127.0.0.1 в файле `hosts`.
====

[[recommendations]]
== Рекомендации авторам
Если где-то в Сети уже есть хорошее руководство - проще разместить ссылку на него.
Для предотвращения утери в будущем - можно использовать https://archive.is/.
Пример сохранённой ссылки на https://archive.is/wip/TJsIF[https://bgerp.ru]

Избегайте больших файлов, они увеличивают размер GIT.

Здесь можно посмотреть link:https://pzdcdoc.org/demo/src/doc/demo.html[примеры] разметки, там же есть ссылка на исходный файл AsciiDoc.

Для отслеживания изменений присутствует <<changes.adoc#, лог>>.

Ссылка на файл описания автора должна быть размещена в начале каждого файла.

AsciiDoc файлы и внутренние ссылки в них именовать с использованием букв латинского алфавита и тире.

[[lang]]
== Многоязычность
Каждый *article.adoc* файл может быть написан на любом языке.
Аббревиатура языка оригинала должен быть указан в квадратных скобках после заголовка статьи.
При выполнении переводов файлы должны называться *article.<LANG_TO>.adoc* и располагаться рядом с оригинальным файлом.

В данный момент поддержка переводов не выполнена, но в перспективе предполагается, что под каждый язык ссылки внутри
файла будут корректироваться для указания на переводной вариант, если он есть.

Ссылка на файл описания переводчика должна быть размещена в начале файла после ссылки на автора.
