= Теория эволюции IT


Unix way - путь научного познания
Раздражают дилетаны

Почему нельзя обозвать диски буковками? А зачем мне типы, оно не может как-нибудь само так?

Хочу нажать на файл и чтобы всё было.

Windows way - улыбчивые маркетологи.

Низкий порог входа против долгосрочных выгод.
Судьба проекта.


Система "всё включено из коробки". Поставил - и забил.

GIT чётко область применения
Дешёвое создание ветки, свободные эксперименты внутри, после перенос чистового варианта изменений одним патчем.
Но тут же полезли "Правильные Wokflow" от непонимающих.

// ================

Связанность, транзакционность.

Реальные вехи:
* 386
* многоядерная революция, compare and swap
* в т.ч. графические чипы с тысячами ядер - нейросети

== Основные свойства
- Типизация - весь код становится связанным, но писать приходится больше.

Статические и динамические языки.
Языки динамические практически невозможно поддержать в IDE.
Их очень дорого

- Унификация - один способ сделать одну вещь. Строки с разными кавычками, форматирование - всё распыляет знания.
Тратится время на изучение отстутствующих различий.

Perl - посмотреть передачу переменных по ссылкам.
Нынешний преемник - Gradle, JavaScript.

Слишком гибкие, слишком много способов сделать одно и то же. Абстракции, отсутствующие в языке изобретаются самостоятельно во фреймворках. Язык не предлагает

Хорошо, когда есть однозначные принципы, когда что делать, лишнего не думать. Единообразный формат, скобки,


- Асинхронность - один поток в браузере, лапша

=== JavaScript
Assembler для браузеров.

options = options || {};

const f = (param) => {
	do something;
}

JSON is cool
data = {a:   }


Очень низкий порог входа и можно писать первый раз очень быстро.

Отсутствии проверки типов (оно и сокращает запись) делает поддержку кода чрезвычайно дорогой.

Можно легко менять типы, только что вот была строка, а присваивается объект.

Явно не задуманные заранее вещи, типа Perl:

// "use strict";

Или импорты в TypeScript, к тому же типизация там не приводит к оптимизации выполнения, браузер
получает тот же JS.


== Всё есть текст


FAR + ConEmu

Держать только нужные окружения открытыми.

Частые операции ускорять, план тестирования.
Скрипты

Сначала файлы переименовывать с _ в начале.

декларативные и итеративные ЯП

связанность программ: типы, сигнатуры
в БД целостность, бесполезные попытки сделать "независимый API"

Управление проектами, ссылку в группе.

Удалить сначала ненужное, уменьшить объём.

Самый плохой код - несвязанный.




Меньше кода лучше, чем больше. Проще и быстрее читать и понимать.

Форматирование и единообразие, плохо, когда много способов сделать одно и то же.
Perl, строки в JS - сегментация решений в сети.
Второй язык - вообще воплощение гибкости, которая его же и погубила.
Язык - это набор соглашений и чем они строже - тем лучше.

== Судьба проекта
Давайте всё заново перепишем. Это проще, разные стороны.
