= UNIX Shell
:toc:

////
[[first-language]]
== Первый язык
В стародавние времена первых компьютеров командная оболочка естественным образом являлась первом языком,
необходимым для освоения каждому. В противном случае просто не было возможности копировать файлы и выполнять другие простые операции.
Позднее, в эпоху низкого порога входа и графических интерфейсов, религия всемогущего клика мышью
по кнопке "Сделать хорошо" на некоторое время отодвинула её в мрачные дебри серверов.

Сегодня, однако, Shell снова на подъеме вместе с GIT, Linux, Docker, а с появлением WSL в Windows 10 его можно использовать повсеместно как универсальный язык для автоматизации рутинных операций. Какие преимущества делают его таким особенным:
[square]
* простая но гибкая концепция текстового интерфейса и запускаемых в нём процессов с результирующими кодами;
* текстовым интерфейсом может пользоваться как человек, так и другая программа;
* вызов может производится на локальной или удалённой машине;
* скрипты легко хранить, переносить, документировать, они органично сочетаются с любым другим программным кодом.

Наиболее популярной оболочкой *NIX сегодня является link:https://ru.wikipedia.org/wiki/Bash[Bash].
link:http://ruslandh.narod.ru/howto_ru/Bash-Prog-Intro/Bash-Prog-Intro.html[Учебник] по языку.

WARNING: Два "языка" по ссылкам внизу способны повредить неокрепшию психику начинающего разработчика либо системного администратора.

В операционных системах Microsoft со времён MS DOS существует жалкий уродец link:https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%BD%D1%8B%D0%B9_%D1%84%D0%B0%D0%B9%D0%BB[Язык .bat файлов]
Не так давно у него появился достойный собрат https://ru.wikipedia.org/wiki/PowerShell[PowerShell]
////

[[bash]]
== Bash
The most popular command interpreter for *NIX is link:https://ru.wikipedia.org/wiki/Bash[Bash].

In Bash scripts is nice seen so named link:https://ru.wikipedia.org/wiki/%D0%A4%D0%B8%D0%BB%D0%BE%D1%81%D0%BE%D1%84%D0%B8%D1%8F_Unix[UNIX Way]
With different combination of simple text processing utilities you can cover almost every scenario.

[[Examples]]
== Examples
// === Print out
// [source, bash]
// ----
// date && tail -f log/bgerp.log | grep 212
// ----

// === Копирование с помощью rsync
// В локальных каталог и обратно.
// [source, bash]
// ----
//
// ----


